### ISSUE TITLE
Latest lib version

### ISSUE THREAD

**Issue by joshbinney** [microsoftgraph/msgraph-sample-azurefunction-csharp#61]
The notify code doesn't work with the latest version of Graph as GetRootParseNode takes a Stream. Also getting an error:
Microsoft.Kiota.Abstractions: Content type application/json does not have a factory registered to be parsed.

Any ideas?

**Comment by jasonjoh** [comment]
@joshbinney I cannot reproduce your error. When you say "latest version", do you mean Microsoft.Graph 5.4.0?

Also, I don't understand this:

> The notify code doesn't work with the latest version of Graph as GetRootParseNode takes a Stream.

`req.Body` is a `Stream`. Are you getting a build error?

https://github.com/microsoftgraph/msgraph-sample-azurefunction-csharp/blob/49a80b54318af295f0f97e0971e5b874b72ee4da/GraphSampleFunctions/Notify.cs#L67-L73

**Comment by joshbinney** [comment]
Yes 5.4. I'm not at my Pc now but I think you had HttpResponseData instead
of HttpResponse no?

**Comment by joshbinney** [comment]
Hey taken another look. It looks as though req.Body is a byte array not a Stream. As for the json factory issue I'm not sure what has caused that, perhaps I've missed something.

**Comment by jasonjoh** [comment]
How are you seeing `req.Body` as a byte array? It's definitely a `Stream` according to the [HttpRequestData.Body docs](https://learn.microsoft.com/dotnet/api/microsoft.azure.functions.worker.http.httprequestdata.body?view=azure-dotnet#microsoft-azure-functions-worker-http-httprequestdata-body) as well as what I'm seeing locally:

![image](https://user-images.githubusercontent.com/8966342/229518287-27847b5e-d935-46b5-9d05-136e98297a3e.png)

![image](https://user-images.githubusercontent.com/8966342/229518422-c1068a5e-51bc-4a2f-aaa8-3aa51f215a25.png)

What version of the Azure tools are you using? You can find this with `func --version`.

Do you have screenshots or text of the errors you're seeing? Are they during compilation or during runtime? If you can point me at a repo with your project that's hitting this error I'd be happy to take a look.

**Comment by joshbinney** [comment]
Hey thanks for all your help so far. Unfortunately I can't share my code as its IP. I found the issue the HttpRequestData, wrong reference. Using the correct lib now and we have a stream! Next issue seems to be that Functions doesn't want to bind to it as its abstract?

"Cannot dynamically create an instance of type 'Microsoft.Azure.Functions.Worker.Http.HttpRequestData'. Reason: Cannot create an abstract class."

**Comment by joshbinney** [comment]
Oh disregard that, found the magic line ConfigureFunctionsWorkerDefaults() in your sample. Just battling some dll hell now!

**Comment by joshbinney** [comment]
Okay after much research and testing here's what I've found. We've gone out of scope of the original question now so let me know if I should make a new thread.

1) It seems that your function project example is using the isolated flavour, mine is using in-process. To get an instance of HttpRequestData as you have, I need to call IHostBuilder.ConfigureFunctionsWorkerDefaults(), but without my own program.cs and therefore my own IHostBuilder I'm not sure how to achieve this. I have a startup class that looks like this:

`[assembly: FunctionsStartup(typeof(TeamsEventProcessor.Startup))]

namespace TeamsEventProcessor
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            ...
        }
    }
}`

2) The other issue I have is Kiota related error " Content type application/json does not have a factory registered to be parsed." Do you know how I can register a factory for that in an in-process function?

Thanks!

**Comment by jasonjoh** [comment]
Ah, great catch. Yes indeed this sample was created as isolated.

Now typically we limit issues in sample repos to the samples themselves. We can't troubleshoot custom code. However, I took a quick look. I created a new function project in-process:

```
func init GraphInProc --worker-runtime dotnet
func new --name Notify --template "HTTP trigger"
```

The function receives an `HttpRequest` instead of an `HttpRequestData`, but the `Body` property is also a `Stream` ([docs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httprequest.body?view=aspnetcore-7.0#microsoft-aspnetcore-http-httprequest-body)). This may be a difference in .NET versions or Azure tools. Did you maybe create your project using an old version of the `func` tool? I'm using 4.0.5095. What's your `TargetFramework` in your csproj file?

Here's what my function's signature looks like:

```csharp
[FunctionName("Notify")]
public static async Task<IActionResult> Run(
    [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
    ILogger log)
```

On the Kiota error - you should not have to register any factories, that's done by the `Microsoft.Graph` package.

**Comment by jasonjoh** [comment]
The Kiota libraries are a dependency of Microsoft.Graph 5.x (well more accurately, Microsoft.Graph.Core 3.x, which is a dependency of Microsoft.Graph). You don't need to add a reference to those libraries.

https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/24d519214038b8c6073177ad65ba64e2b91b7f40/src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj#L62-L64

When you create a new `GraphServiceClient`, the library registers all of the serializers/deserializers:

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/8bd7ddca432ea45cd8c1a177e18542e676962673/src/Microsoft.Graph/Generated/BaseGraphServiceClient.cs#L362-L374

I'd recommend opening an issue in the https://github.com/microsoftgraph/msgraph-sdk-dotnet repo with repro steps for the error.

**Comment by joshbinney** [comment]
OK excellent. Thanks for your help mate, much appreciated!
